### ISSUE TITLE
Не следовать камерой за направлением взгляда

### ISSUE THREAD

**Issue by kswaldemar** [All-Cups/aicup22#10]
Иначе камеру очень сильно мотает, если выделенный юнит активно крутиться.
Также было бы удобно, если бы в паузе камера не возвращалась к выделенному юниту после движения.

https://user-images.githubusercontent.com/10009947/178030381-3d3fd2e3-41cb-420b-ac9e-92b228c58a75.mov

**Comment by Karloid** [comment]
неистово плюсую - укачивает :>

**Comment by Karloid** [comment]
лайфхак - нажимаем ПКМ в визуализаторе и камера "расфокусируется"

**Comment by kuviman** [comment]
На сайте обновление будет позже, в локальном уже сделано
