### ISSUE TITLE
Пояснения по подсчету рейтинга на базе счета.

### ISSUE THREAD

**Issue by antain** [All-Cups/aicup22#17]
После игры 385627 счет упал с 28 (примерно 45 был в рейтинге) до 18 (около 115). 
При счете за игру 5 395.333.

Можете посмотреть, правильно ли все посчиталось... Или может расскажете формулу подсчета рейтинга?

**Comment by Nirenamid** [comment]
Внутриигровой счет (5 395.333) не связан с расчетом рейтинга. 
На рейтинг влияет место, которое занял игрок в партии (с 1-го по 6-е), текущий рейтинг самого игрока и рейтинги его соперников.

Упрощенно говоря:
- обыграл более сильных - рейтинг вырастет сильно
- обыграл слабых или равных - рейтинг вырастет незначительно
- проиграл равным - рейтинг упадет незначительно
- проиграл более слабым - рейтинг упадет сильно

К сожалению после обнуления рейтинга периода бета-тестирования просмотреть историю конкретной битвы уже нет возможности. Скорее всего та игра совпала с моментом перевыбора решения (при котором рейтинг полностью сбрасывается в 0), то есть была такая цепочка изменений: 28->0->18
