### ISSUE TITLE
Увеличить максимальное "зум аут" в визуализаторе / локал раннере

### ISSUE THREAD

**Issue by Karloid** [All-Cups/aicup22#21]
Хочется окидывать взглядом всю карту сразу
скриншот из браузера, текущий максимальный zoom out
Chrome, macos
<img width="1039" alt="image" src="https://user-images.githubusercontent.com/2398460/178099273-5727199f-f5c2-47d3-b50b-921b58f58166.png">

**Comment by kuviman** [comment]
На сайте обновление будет позже, в локальном уже сделано
