### ISSUE TITLE
[bug] Визуализатор на сайте не показывает хелс бары, иконки оружия и т.д.

### ISSUE THREAD

**Issue by Karloid** [All-Cups/aicup22#22]
chrome Version 103.0.5060.53 (Official Build) (x86_64)
MacBook Pro (Retina, 15-inch, Mid 2015)

большую часть времени не видны хелс бары, иконки оружия, прогрес бары действий

<img width="640" alt="image" src="https://user-images.githubusercontent.com/2398460/178099799-35b0324b-e5e8-41f9-931e-699a749c80ed.png">

https://user-images.githubusercontent.com/2398460/178099766-d20eb221-f9e6-48e5-8d4a-90150e3ecda8.mov

**Comment by kuviman** [comment]
готово
