### ISSUE TITLE
Координаты текстом в ЛР

### ISSUE THREAD

**Issue by DragoonXen** [All-Cups/aicup22#25]
При дебаге частая ситуация - в ЛР совсем непонятно где какая точка, а код клиента остановлен на брейкпоинте. В это время рисовать что-то в ЛР затруднительно.

Просьба повесить вывод текстом координат курсора на какую-нибудь клавишу :)

**Comment by kuviman** [comment]
https://github.com/All-Cups/aicup22/releases/tag/v1.2.0
