### ISSUE TITLE
[Feature Request] добавить счетчик ALIVE в отображение приложение (локал раннер)

### ISSUE THREAD

**Issue by Karloid** [All-Cups/aicup22#30]
Хочется (для вовлеченности\зрелищности) понимать при просмотре сколько осталось живых волшебников

пример из пубга:

![image](https://user-images.githubusercontent.com/2398460/178118841-e421a56e-f6fb-4d4f-a8a9-c36b6842d868.png)

**Comment by kuviman** [comment]
https://github.com/All-Cups/aicup22/releases/tag/v1.2.0
