### ISSUE TITLE
[Feature Request] добавить лейблы с именами игроковв отображение приложения (локал раннера)

### ISSUE THREAD

**Issue by Karloid** [All-Cups/aicup22#32]
Хочется что бы живые игроки были более заметны и отличимы на фоне остальных ботов.
Для отображения можно добавить настройку.

примерный вид:
![image](https://user-images.githubusercontent.com/2398460/178119234-ade55e92-fc6e-4c00-a3e5-6f14400cedf4.png)

![image](https://user-images.githubusercontent.com/2398460/178119017-c055534e-052d-4604-afd7-0053fb3adeee.png)

**Comment by kuviman** [comment]
https://github.com/All-Cups/aicup22/releases/tag/v1.2.0
