### ISSUE TITLE
Баг отображения номера тика в ЛР

### ISSUE THREAD

**Issue by DragoonXen** [All-Cups/aicup22#35]
Номер тика на кадре нарисован около юнита (нижняя строка)
Мотаем назад на паузе 
![image](https://user-images.githubusercontent.com/1372016/178163407-658f3295-8290-418a-920a-300d28255b97.png)
видим баг.

Доходим до нуля и теперь вперёд
![image](https://user-images.githubusercontent.com/1372016/178163425-95383922-af65-4b28-a74b-137f4cdf8e10.png)
баг фиксится

**Comment by kuviman** [comment]
should be fixed
