### ISSUE TITLE
Localrunner падает с самого начала.

### ISSUE THREAD

**Issue by Kangar0o** [All-Cups/aicup22#42]
Скачал архив, распаковал, запустил - ничего. Что я делаю не так?

C:\WINDOWS\system32>H:\app-windows\aicup22.exe
[INFO  ugli::context] GL version: "4.0.0 - Build 10.18.10.4885"
[ERROR batbox::logger] panicked at 'called `Result::unwrap()` on an `Err` value: Shader compilation failed:
    ERROR: 0:3: 'inverse' : built-in redefinition is not allowed
    ERROR: 0:3: 'inverse' : built-in redefinition is not allowed
    ERROR: 0:3: 'inverse' : built-in redefinition is not allowed
    ERROR: 0:158: 'v_color' : undeclared identifier
    ERROR: 0:158: 'a_color' : undeclared identifier
    ERROR: 0:159: 'u_projection_matrix' : undeclared identifier
    ERROR: 0:159: 'u_view_matrix' : undeclared identifier
    ERROR: 0:159: 'u_model_matrix' : undeclared identifier
    ERROR: 0:159: 'a_pos' : undeclared identifier
    ERROR: 0:159: 'constructor' : not enough data provided for construction

    ', /usr/local/cargo/git/checkouts/geng-a1d76f5475a34e9a/bc1f49b/crates/geng/src/draw_2d/mod.rs:131:18
[ERROR batbox::logger]    0: backtrace::backtrace::trace
       1: backtrace::capture::Backtrace::new
       2: batbox::logger::init_with::{{closure}}
       3: std::panicking::rust_panic_with_hook
                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library\std\src/panicking.rs:702:17
       4: std::panicking::begin_panic_handler::{{closure}}
                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library\std\src/panicking.rs:588:13
       5: std::sys_common::backtrace::__rust_end_short_backtrace
                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library\std\src\sys_common/backtrace.rs:138:18
       6: rust_begin_unwind
                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library\std\src/panicking.rs:584:5
       7: core::panicking::panic_fmt
                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library\core\src/panicking.rs:142:14
       8: core::result::unwrap_failed
                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library\core\src/result.rs:1785:5
       9: geng::context::Geng::new_with
      10: codegame::runner::run_with
      11: aicup22::main
      12: std::sys_common::backtrace::__rust_begin_short_backtrace
      13: std::rt::lang_start::{{closure}}
      14: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc\library\core\src\ops/function.rs:280:13
          std::panicking::try::do_call
                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library\std\src/panicking.rs:492:40
          std::panicking::try
                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library\std\src/panicking.rs:456:19
          std::panic::catch_unwind
                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library\std\src/panic.rs:137:14
          std::rt::lang_start_internal::{{closure}}
                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library\std\src/rt.rs:128:48
          std::panicking::try::do_call
                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library\std\src/panicking.rs:492:40
          std::panicking::try
                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library\std\src/panicking.rs:456:19
          std::panic::catch_unwind
                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library\std\src/panic.rs:137:14
          std::rt::lang_start_internal
                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library\std\src/rt.rs:128:20
      15: main
      16: __tmainCRTStartup
                 at /./mingw-w64-crt/crt/crtexe.c:334
      17: mainCRTStartup
                 at /./mingw-w64-crt/crt/crtexe.c:212
      18: <unknown>
      19: <unknown>

**Comment by kuviman** [comment]
Ошибка должна быть исправлена в 1.2.2, переоткройте ишью если не так
