### ISSUE TITLE
Возможность задавать начальный размер окна в LR

### ISSUE THREAD

**Issue by kswaldemar** [All-Cups/aicup22#5]
Для запуска из консоли с кастомным конфигом была бы полезна возможность задавать размеры окна.
Сейчас небольшое окошко появляется по центру, и его приходится растягивать руками каждый раз.

Было бы круто иметь опцию в LR, например `--window-size=1280x800`
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/10009947/177945865-5ddfaf17-9e39-4523-8278-fc7b1ac80cd0.png">

**Comment by kuviman** [comment]
готово
