### ISSUE TITLE
Номер тика в debugUpdate меньше чем отображается в приложении

### ISSUE THREAD

**Issue by alex-dudin** [All-Cups/aicup22#54]
В метод debugUpdate достаточно часто приходит номер тика (displayedTick) меньший чем в данный момент отображается в приложении. Такое возникает достаточно часто.

Пример на скриншоте, мы смотрим на тик 80, но в debugUpdate нам постоянно посылается displayedTick=79, из-за этого отладочная отрисовка выполняется для предыдущего тика.

![debug_interface_tick_bug](https://user-images.githubusercontent.com/64810764/179357029-079f54ef-cffc-4b62-98ad-3f9cd41267a8.png)

**Comment by kuviman** [comment]
Исправлено в версии 1.2.3
