### ISSUE TITLE
Нет возможности настроить компиляцию модулей расширения Python/CPython

### ISSUE THREAD

**Issue by mr2dark** [All-Cups/aicup22#57]
Сейчас есть возможность только компилировать отдельные Cython-файлы формата `*.pxd`. При этом выдаётся предупреждение
```/usr/local/lib/python3.10/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release!``` 
Однако полноценным и рекомендуемым вариантом для Cython является использование файла `setup.py` для конфигурации компиляции. Из [Building Cython Code](https://cython.readthedocs.io/en/stable/src/quickstart/build.html#building-cython-code):
> There are several ways to build Cython code:
> - Write a distutils/setuptools `setup.py`. This is the normal and recommended way.
> ...

В `setup.py` можно указывать и вышеупомянутый `language_level` и, например, добавить пути к заголовочным файлам `numpy`.

Другим важным нюансом является то, у Cython есть [Pure Python Mode](https://cython.readthedocs.io/en/stable/src/tutorial/pure.html), в рамках которого Cython может компилировать `*.py` с определенными декораторами внутри.
Только при использовании `setup.py` можно указать те `*.py` файлы, которые требуют компиляции, не трогая остальные. 

Таким образом необходимо при наличия в исходниках `setup.py` компилировать модули расширения с его использованием.

**Comment by mr2dark** [comment]
Сделал Pull Request с необходимыми изменениями: https://github.com/All-Cups/aicup22/pull/55

**Comment by kuviman** [comment]
PR замержен
